# Generated by Django 3.2.2 on 2021-08-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20210811_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now_add=True, default='2021-08-01', verbose_name='Дата операции'),
            preserve_default=False,
        ),
    ]
