name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on: [push, pull_request]
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
    # Чекаутим код
    - uses: actions/checkout@master
    # Устанавливаем python нужной версии
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: Install poetry
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install poetry
    - name: Install requirements
      # Устанавливаем зависимости
      run: |
        cd server
        python -m poetry install
    - name: Run tests
      run: |
        python -m pytest
